### PR TITLE
fix #1054: if it is a new one, it should be added at first.

### LINKED ISSUE #1054: "Downloading" item is inserted into wrong position
In downloading, when open download panel open before the item inserted in, it will be add in the end. But open it again, it will be at first.

### PR DESCRIPTION
**Pull request by WeiWW**
as title

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/widget/DownloadListAdapter.java [hunk 1]
```diff
@@ -86,7 +86,7 @@ public void updateItem(DownloadInfo downloadInfo){
         }
 
         if (index == -1){
-            mDownloadInfo.add(downloadInfo);
+            mDownloadInfo.add(0,downloadInfo);
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/widget/DownloadListAdapter.java]: Extra space needed :P

**Comment by mTwTm** [comment]
Fixes #1054
