### PR TITLE
Block non-http/https download links

### LINKED ISSUE #605: block non-http/https download links
Releated to #522 we should at least first block the crashing.

### PR DESCRIPTION
**Pull request by joseph-yar**
- Closes #605

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java [hunk 1]
```diff
@@ -554,7 +554,14 @@ private void queueDownload(Download download) {
         // So, for now we always save file to DIRECTORY_DOWNLOADS
         final String dir = Environment.DIRECTORY_DOWNLOADS;
 
-        final DownloadManager.Request request = new DownloadManager.Request(Uri.parse(download.getUrl()))
+        // block non-http/https download links
+        Uri downloadUri = Uri.parse(download.getUrl());
+        if(!TextUtils.equals(downloadUri.getScheme(), "http") && !TextUtils.equals(downloadUri.getScheme(), "https")) {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java]: Let's just use android.webkit.URLUtil.isNetworkUrl(download.getUrl()) for simplicity here.

File: app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java [hunk 2]
```diff
@@ -554,6 +554,12 @@ private void queueDownload(Download download) {
         // So, for now we always save file to DIRECTORY_DOWNLOADS
         final String dir = Environment.DIRECTORY_DOWNLOADS;
 
+        // block non-http/https download links
+        if(!URLUtil.isHttpsUrl(download.getUrl())) {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java]: Consider HTTP and HTTPS, use URLUtil.isNetworkUrl
