### PR TITLE
Fix after deleting screenshot image, screenshot preview still exists …

### LINKED ISSUE #642: After deleting screenshot image, screenshot preview still exists on "My shots"
Actual result: 
1. delete screenshot image
2. return to "My shots" panel
3. the deleted screenshot preview still on the panel

Expected result
1. delete screenshot image
2. return to "My shots" panel
3. the deleted screenshot should be removed from "My shots" panel

Build: 0.4.790.beta

### PR DESCRIPTION
**Pull request by joseph-yar**
…on "My shots"

- Closes #642

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/screenshot/ScreenshotItemAdapter.java [hunk 1]
```diff
@@ -161,19 +161,16 @@ public void onQueryComplete(List result) {
...
 
-    @Override
-    public void onDeleteComplete(int result, long id) {
-        if (result > 0) {
-            if (id < 0) {
-                final int count = mItems.size();
-                mItems.clear();
-                notifyItemRangeRemoved(0, count);
+    public void onItemDelete(long id) {
+        if (id < 0) {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/screenshot/ScreenshotItemAdapter.java]: The id should always be >=0 since we're not feeding -1 like we do in clear_browsing_history. Should be safe to just do the things in else {} here.
